# Generated by Django 5.1.7 on 2025-03-17 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_remove_event_date_event_date_from_event_date_to'),
    ]

    operations = [
    ]
