# Generated by Django 5.1.7 on 2025-03-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20250317_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_from',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='date_to',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
