# Generated by Django 5.1.7 on 2025-03-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_event_date_from_alter_event_date_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('event_manager', 'Event Manager')], max_length=50),
        ),
    ]
